### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by aimalamiri** [aimalamiri/Ruby-Catalog#32]
## Finished creating tasks and the Kanban board

We're a team of 3 people listed bellow
1. @aimalamiri
2. @mwenyoa 
3. @Yazino12 

Here is a link to our project
https://github.com/aimalamiri/Ruby-Catalog/projects/1

**Comment by Davidosky007** [comment]
Hi @aimalamiri @mwenyoa @Yazino12 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Issue has all the right details 👍 
* Link to kanban board ok 👍 
* Board created properly 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
